# Generated by Django 4.2.1 on 2024-10-30 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0004_alter_unscheduledworkorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unscheduledworkorder',
            name='closed_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='unscheduledworkorder',
            name='purchase_order',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
